---
title: "PR9 - Package & Web Scraping"
author: "김서준"
date: "2023년 11월 7일"
output: html_document
---
# 1. package 기본

- R에서 기본적으로 제공하는 함수 외에 다른 프로그래머들이 필요하다고 생각해서 만들어 놓은 함수들의 모음
- 이것을 보통 library 또는 API라고 칭함
- R에서는 보통 CRAN에서 R재단이 인정한 패키지들을 공유
- 비공짓적이지만 개인이 만들어서 공유한 패키지들이 있고 보통 github에 업로드 돼 있음

## 1.1. 설치

- 설치 명령어: `install.packages()
- 다음 시간 사용할 크롤링 관련 패키지 설치

```{r}
#install.packages("rvest")
#install.packages("httr")
#install.packages("RSelenium")
```

## 1.2. 불러오기

 + `libray(package 이름)` : 설치되어 있는 패키지를 불러옴
 + `require`(package 이름)` : 불러오려는 시도를 하고 logical한 return 값을 반환
 
- `require()`도 결과적으로 `library()`와 동일한 기능을 하지만, 결과값에서 차이가 나게된다.

```{R}
x <- library(rvest);x
x <- require(rvest);x
```

```{R}
#해당패키지가 없다고 에러가 뜨며 결과 knit시 에러가 발생할 수 있는 부분.
#library(chorn)

#해당 패키지가 없더라도 에러메시지가 뜨지 않고 knit를 정상적으로 진행할 수 있다.
require(chorn)
```


## 1.3. 패키지 업데이트
 - 패키지 개발자가 자신이 만든 패키지의 기능을 보완하거나, R버전이 업데이트 되어 호환이 되게 수정하거나 오류사항을 수정
 - 명령어는 `update.packages(패키지 이름)`
 - R Studio 를 사용한다면 우측 하단에 packages 탭이 보이는데 해당 탭 바로 밑에 update라는 항목이 보인다.
 - 이걸 누르고 원하는 패키지 혹은 전체를 선택하고 업데이트를 누르면 됨
 
```{R}
#update.packages("rvest")
```

## 1.4. 불러온 패키지 사용중지

```{R}
#detach("packages:ggplot2", unload = T)
```

# 2. package 고급

## 2.1. package에서 함수 가져오기
- 다양한 패키지들을 불러오다 보면, 동일한 함수명을 사용해서 서로 충돌할 때가 있다.
- 그럴때는 `패키지명::함수명`으로 어떤 패키지에서 해당 함수를 사용할 것인지 명시해서 문제를 해결할 수 있다.
```{R}
#require(plyr)
#require(Hmisc)
#require(chron)
#require(tseries)

#plyr::summarize
#Hmisc::summarize
#chorn::is.weekend()
#tseries::is.weekend()
```
- **실습**:
```{R}
library(readxl)
readxl::read_xlsx("student.xlsx")
```

## 2.3. 편리한 사용자 정의 함수
- 해당 함수는 패키지명으로 구성된 문장형 벡터를 입력으로 받아서, 설치 및 불러오기를 동시에 진행하는 함수입니다.
- 만약 해당 패키지가 이미 설치되어 있는 패키지라면 바로 설치과정을 생략하고 바로 불러오기를 진행하게 됩니다.
```{R}
take <- function(x) {
  for (i in x) {
    if (!is.element(i, .packages(all.available = TRUE))) {
      install.packages(i)
    }
    library(i, character.only = TRUE)
  }
}
take(c("rvest", "httr"))
```
# 3. `devtools`
- `devtools`의 주 목적은 패키지 개발에 필요한 많은 작업들을 단순화시키는 것이다. 뿐만 아니라 비공식 패키지 버전 관리의 측면에서는 상당히 중요한 패키지 이다.
## 3.1. 비공식 패키지 설치
- CRAN에서 제공하는 패키지가 아닌, github에 공개되어 있는 다영한 패키지들고 설치하여 사용할 수 있다.

```{R}
#install.packages("devtools")
library(devtools)

#install_github("패키지")
```

## 3.2. 원하는 버전 설치

- R의 패키지들이 최신 버전에 맞춰서 업데이트가 되지 않았다면, 이전 버전의 패키지를 사용해야만 하는 경우들이 있으며 이때 사용하는 것이 `devtools`의 `install_version()`입니다.
- `install_version("패키지명", version = "버전명", repos = "https://cran.us.r-project.org")`
  + 패키지명과 어떤 버전명을 지정해주면 되며, **repos**는 어떤 서버네서 핻ㅇ 내용을 다운받을지 지정해주는 것이다.
  
  
```{R}
#library(devtools)
#remove.packages("ggplot2")
#install_version("ggplot2", version = "0.9.1", repos = "https://cran.us.r-project.org")
#packageVersion("ggplot2)
```
- 이 과정을 실습해 봤다면 `ggplot2`를 지운 후 밑의 `tidyverse`로 설치를 진행하면 된다.
```{R}
# remove.packages("ggplot2)
```
# 4. `tidyverse`

- tidyverse`는 `dplyr`, `tidyr`, `ggplot2` 등, R 프로그래밍의 핵심 패키지들을 한번에 설치 및 관리해주는 패키지이다.
```{R}
#install.packages("tidyverse")
#install.packages("glue")
library(tidyverse)
```

# 패키지 연습문제

### github에 개인 패키지 만들기

```{R}
#install_github("selffish234/selffish234R")
library(selffish234R)
selffish234R::double(3)
```
# rvest를 이용하여 아주대 공지사항 크롤링

```{R}
library(rvest)

title <- NULL
dept <- NULL
date <- NULL

for (i in 1:2) {
  url <- "https://www.ajou.ac.kr/kr/ajou/notice.do?mode=list&&articleLimit=10&article.offset="
  urls <- paste0(url, (i-1)*10)
  html_source <- read_html(urls)
  
  for (i in 1:10) {
    T.selector <- paste0("#cms-content > div > div > div.bn-list-common02.type01.bn-common-cate > table > tbody > tr:nth-child(", i, ") > td.b-td-left > div > a")
    title.nodes <- html_nodes(html_source, T.selector)
    T.title <- html_text(title.nodes)
    title <- c(title, T.title)
    
    D.selector <- paste0("#cms-content > div > div > div.bn-list-common02.type01.bn-common-cate > table > tbody > tr:nth-child(", i, ") > td:nth-child(5)")
    dept.nodes <- html_nodes(html_source, D.selector)
    T.dept <- html_text(dept.nodes)
    dept <- c(dept, T.dept)
    
     date.selector <- paste0("#cms-content > div > div > div.bn-list-common02.type01.bn-common-cate > table > tbody > tr:nth-child(", i, ") > td:nth-child(6)")
    date.nodes <- html_nodes(html_source, date.selector)
    T.date <- html_text(date.nodes)
    date <- c(date, T.date)
    
  }
}

```


```{R}
ajou.notice <- data.frame(title, date, dept)

ajou.notice[,1] <- gsub("\n", "", ajou.notice[,1])
ajou.notice[,1] <- gsub("\t", "", ajou.notice[,1])
ajou.notice[,1] <- gsub("\r", "", ajou.notice[,1])

head(ajou.notice)
```

# Rselenium을 이용한 '관광' 분야의 연구개발 성과 크롤링코드

```{R}
library(RSelenium)
library(httr)
library(dplyr)
remDR <- remoteDriver(remoteServerAddr="localhost", port=4445L, browserName="chrome")
remDR$open()
remDR$navigate('https://www.ntis.go.kr/outcomes/popup/srchRstList.do')

find_ <- remDR$findElement(using="css", value="#searchKey")
find_$clickElement()
find_$sendKeysToElement(list("관광"))

find_click <- remDR$findElement(using="css", value="#btnHeaderSearch")
Sys.sleep(1)
find_click$clickElement()

Sys.sleep(1)
research_ <- remDR$findElement(using='xpath', value='/html/body/div[2]/div[3]/form/div[5]/div/div[4]/div[1]/table/tbody/tr[6]/td/ul/li[1]/input')
research_$clickElement()
filter_click <- remDR$findElement(using='xpath', value='/html/body/div[2]/div[3]/form/div[5]/div/button')
filter_click$clickElement()
research_ <- remDR$findElement(using = 'css', value = paste0('#content > div.layoutBox > div.list_box > div:nth-child(2) > div > a.rstTitle'))
research_$clickElement()

myswitch <- function (remDr, windowId)
{
  qpath <- sprintf("%s/session/%s/window", remDr$serverURL,
                   remDr$sessionInfo[["id"]])
  remDr$queryRD(qpath, "POST", qdata = list(handle = windowId))
}
check_handle <- FALSE
count <- 0
while(!check_handle || count > 20){
  count <- count + 1
  windows_handles <- remDR$getWindowHandles()
  if(length(windows_handles) < 2){
    Sys.sleep(1)
  }else{
    check_handle <- TRUE
  }
}

myswitch(remDR, windows_handles[[2]])
#### 여기까지.
research_title <- remDR$findElement(using='css', value='#content > div.po_rel > div.outcomesheader_wrap > dl > dd > span.head')
research_title$getElementText()[[1]]
research_date <- remDR$findElement(using='css', value='#content > div.po_rel > div.defaultInfo_wrap > div.defaultInfo > table > tbody > tr:nth-child(4) > td:nth-child(4)')
research_date$getElementText()[[1]]
research_abstract <- remDR$findElement(using='css', value='#content > div.po_rel > div.defaultInfo_wrap > div.defaultInfo > dl > dd')
research_abstract$getElementText()[[1]]
remDR$closeWindow()
myswitch(remDR, windows_handles[[1]])

```

### 문제1
```{R}
```

```{R}
```

```{R}
```

```{R}
```

```{R}
```
